- name: ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./script
        dest: /home/ubuntu/script
        owner: ubuntu
        group: ubuntu

    - name: Create a docker network
      docker_network:
        name: my-network
    - name: Re-create a MySQL container
      docker_container:
        name: quanndm2906-mysql
        image: mysql:8.0
        networks:
          - name: my-network
            aliases:
              - my-network
        env:
          MYSQL_ROOT_PASSWORD: 8NqUH_rNw58JLpqRp
          MYSQL_DATABASE: db_example
        detach: true
        state: started
        recreate: yes
        exposed_ports:
          - 3306
        pull: true
        comparisons:
          image: strict

    - name: SLEEP now !!!
      shell: sleep 15 && sudo docker exec -i quanndm2906-mysql mysql --user=root --password=8NqUH_rNw58JLpqRp < script

    - name: Re-create a Spring container
      docker_container:
        name: quanndm2906-springboot
        image: quanndm2906/springboot
        networks:
          - name: my-network
            aliases:
              - my-network
        state: started
        recreate: yes
        exposed_ports:
          - 8080
        detach: true
        published_ports:
          - 8080:8080
        pull: true
        comparisons:
          image: strict

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true